# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calc.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

# Класс инициализации программы.


class Ui_CaculatorWin(object):
    def setupUi(self, CaculatorWin):
        # Найстройка размера окна программы.
        weight = 440
        height = 450
        CaculatorWin.setObjectName("CaculatorWin")
        CaculatorWin.resize(weight, height)

        # Фиксирование размера окна.

        CaculatorWin.setMinimumSize(QtCore.QSize(weight, height))
        CaculatorWin.setMaximumSize(QtCore.QSize(weight, height))

        # Добавление иконки.

        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon.png"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        CaculatorWin.setWindowIcon(icon)

        self.row_lable = ["Запрос", "Ответ"]

        # Инициализация вкладок программы.

        self.TabsMain = QtWidgets.QTabWidget(CaculatorWin)
        self.TabsMain.setGeometry(QtCore.QRect(6, -1, 431, 451))
        self.TabsMain.setObjectName("TabsMain")

        # Создание вкладки с историей.

        self.TabHistory = QtWidgets.QWidget()
        self.TabHistory.setObjectName("TabHistory")

        # Кнопка для обновления истории.

        self.ButtonUpdate = QtWidgets.QPushButton(self.TabHistory)
        self.ButtonUpdate.setGeometry(QtCore.QRect(0, 375, 221, 41))
        self.ButtonUpdate.setObjectName("ButtonUpdate")

        # Таблица для отображения истории.

        self.TableHistory = QtWidgets.QTableWidget(self.TabHistory)
        self.TableHistory.setGeometry(QtCore.QRect(5, 11, 411, 355))
        self.TableHistory.setObjectName("TableHistory")
        self.TableHistory.setColumnCount(3)  # Количество колонок.
        self.TableHistory.setRowCount(0)

        # Кнопка для копирования запросов в окно калькулятора.

        self.ButtonCopy = QtWidgets.QPushButton(self.TabHistory)
        self.ButtonCopy.setGeometry(QtCore.QRect(230, 375, 191, 41))
        self.ButtonCopy.setObjectName("ButtonCopy")

        # Создание вкладки справочника.

        self.TabsMain.addTab(self.TabHistory, "")
        self.TabGuide = QtWidgets.QWidget()
        self.TabGuide.setObjectName("TabGuide")

        # Создание вкладок справочника.

        self.TabsCo = QtWidgets.QTabWidget(self.TabGuide)
        self.TabsCo.setGeometry(QtCore.QRect(-4, -1, 431, 431))
        self.TabsCo.setObjectName("TabsCo")

        # Создание вкладки с ф-ми сок-ного умножения.

        self.TabMulti = QtWidgets.QWidget()
        self.TabMulti.setObjectName("TabMulti")

        # Текст вкладки с ф-ми сок-ного умножения.

        self.TextMulti = QtWidgets.QTextBrowser(self.TabMulti)
        self.TextMulti.setGeometry(QtCore.QRect(10, 5, 411, 380))
        self.TextMulti.setObjectName("TextMulti")

        self.TabsCo.addTab(self.TabMulti, "")

        # Создание вкладки с ф-ми площадей фигур.

        self.TabS = QtWidgets.QWidget()
        self.TabS.setObjectName("TabS")

        # Текст вкладки с ф-ми площадей фигур.

        self.TextS = QtWidgets.QTextBrowser(self.TabS)
        self.TextS.setGeometry(QtCore.QRect(10, 5, 411, 380))
        self.TextS.setObjectName("TextS")

        self.TabsCo.addTab(self.TabS, "")

        self.TabsMain.addTab(self.TabGuide, "")

        # Создание вкладки калькулятора.

        self.TabsCalc = QtWidgets.QWidget()
        self.TabsCalc.setObjectName("TabsCalc")

        # Создание дисплея калькулятора.

        self.CalculatorDisplay = QtWidgets.QTextBrowser(self.TabsCalc)
        self.CalculatorDisplay.setGeometry(QtCore.QRect(4, 10, 421, 131))
        self.CalculatorDisplay.setObjectName("CalculatorDisplay")

        # Создание групп кнопок.

        self.LayoutWidget = QtWidgets.QWidget(self.TabsCalc)
        self.LayoutWidget.setGeometry(QtCore.QRect(4, 149, 421, 261))
        self.LayoutWidget.setObjectName("LayoutWidget")

        self.GroupButtons = QtWidgets.QGridLayout(self.LayoutWidget)
        self.GroupButtons.setContentsMargins(0, 0, 0, 0)
        self.GroupButtons.setObjectName("GroupButtons")

        # Кнопка 2.

        self.pushButton2 = QtWidgets.QPushButton(self.LayoutWidget)
        self.pushButton2.setObjectName("pushButton2")

        self.GroupButtons.addWidget(self.pushButton2, 2, 1, 1, 1)

        # Кнопка 0.

        self.pushButton0 = QtWidgets.QPushButton(self.LayoutWidget)
        self.pushButton0.setObjectName("pushButton0")

        self.GroupButtons.addWidget(self.pushButton0, 6, 0, 1, 1)

        # Кнопка открывающая скобка.

        self.pushButton_leftbrackets = QtWidgets.QPushButton(self.LayoutWidget)
        self.pushButton_leftbrackets.setObjectName("pushButton_leftbrackets")

        self.GroupButtons.addWidget(self.pushButton_leftbrackets, 6, 1, 1, 1)

        # Кнопка 8.

        self.pushButton8 = QtWidgets.QPushButton(self.LayoutWidget)
        self.pushButton8.setObjectName("pushButton8")

        self.GroupButtons.addWidget(self.pushButton8, 4, 1, 1, 1)

        # Кнопка очищения.

        self.pushButton_Clear = QtWidgets.QPushButton(self.LayoutWidget)
        self.pushButton_Clear.setObjectName("pushButton_Clear")

        self.GroupButtons.addWidget(self.pushButton_Clear, 4, 3, 1, 1)

        # Кнопка 4.

        self.pushButton4 = QtWidgets.QPushButton(self.LayoutWidget)
        self.pushButton4.setObjectName("pushButton4")

        self.GroupButtons.addWidget(self.pushButton4, 3, 0, 1, 1)

        # Кнопка 9.

        self.pushButton9 = QtWidgets.QPushButton(self.LayoutWidget)
        self.pushButton9.setObjectName("pushButton9")

        self.GroupButtons.addWidget(self.pushButton9, 4, 2, 1, 1)

        # Кнопка 5.

        self.pushButton5 = QtWidgets.QPushButton(self.LayoutWidget)
        self.pushButton5.setObjectName("pushButton5")

        self.GroupButtons.addWidget(self.pushButton5, 3, 1, 1, 1)

        # Кнопка косинуса.

        self.pushButton_cos = QtWidgets.QPushButton(self.LayoutWidget)
        self.pushButton_cos.setObjectName("pushButton_cos")

        self.GroupButtons.addWidget(self.pushButton_cos, 7, 1, 1, 1)

        # Кнопка точки.

        self.pushButton_dot = QtWidgets.QPushButton(self.LayoutWidget)
        self.pushButton_dot.setObjectName("pushButton_dot")

        self.GroupButtons.addWidget(self.pushButton_dot, 2, 3, 1, 1)

        # Кнопка 1.

        self.pushButton1 = QtWidgets.QPushButton(self.LayoutWidget)
        self.pushButton1.setObjectName("pushButton1")

        self.GroupButtons.addWidget(self.pushButton1, 2, 0, 1, 1)

        # Кнопка плюса.

        self.pushButton_Add = QtWidgets.QPushButton(self.LayoutWidget)
        self.pushButton_Add.setObjectName("pushButton_Add")

        self.GroupButtons.addWidget(self.pushButton_Add, 0, 0, 1, 1)

        # Кнопка умножение.

        self.pushButton_Multiply = QtWidgets.QPushButton(self.LayoutWidget)
        self.pushButton_Multiply.setObjectName("pushButton_Multiply")

        self.GroupButtons.addWidget(self.pushButton_Multiply, 0, 2, 1, 1)

        # Кнопка деления.

        self.pushButton_div = QtWidgets.QPushButton(self.LayoutWidget)
        self.pushButton_div.setObjectName("pushButton_div")

        self.GroupButtons.addWidget(self.pushButton_div, 0, 3, 1, 1)

        # Кнопка закрывающей скобки.

        self.pushButton_rightbrackets = QtWidgets.QPushButton(self.LayoutWidget)
        self.pushButton_rightbrackets.setObjectName("pushButton_rightbrackets")

        self.GroupButtons.addWidget(self.pushButton_rightbrackets, 6, 2, 1, 1)

        # Кнопка остаточного деления.

        self.pushButton_mod = QtWidgets.QPushButton(self.LayoutWidget)
        self.pushButton_mod.setObjectName("pushButton_mod")

        self.GroupButtons.addWidget(self.pushButton_mod, 3, 3, 1, 1)

        # Кнопка синуса.

        self.pushButton_sin = QtWidgets.QPushButton(self.LayoutWidget)
        self.pushButton_sin.setObjectName("pushButton_sin")

        self.GroupButtons.addWidget(self.pushButton_sin, 7, 0, 1, 1)

        # Кнопка 3.

        self.pushButton3 = QtWidgets.QPushButton(self.LayoutWidget)
        self.pushButton3.setObjectName("pushButton3")

        self.GroupButtons.addWidget(self.pushButton3, 2, 2, 1, 1)

        # Кнопка 6.

        self.pushButton6 = QtWidgets.QPushButton(self.LayoutWidget)
        self.pushButton6.setObjectName("pushButton6")

        self.GroupButtons.addWidget(self.pushButton6, 3, 2, 1, 1)

        # Кнопка 7.

        self.pushButton7 = QtWidgets.QPushButton(self.LayoutWidget)
        self.pushButton7.setObjectName("pushButton7")

        self.GroupButtons.addWidget(self.pushButton7, 4, 0, 1, 1)

        # Кнопка минуса.

        self.pushButton_Minus = QtWidgets.QPushButton(self.LayoutWidget)
        self.pushButton_Minus.setObjectName("pushButton_Minus")

        self.GroupButtons.addWidget(self.pushButton_Minus, 0, 1, 1, 1)

        # Кнопка квадратного корня.

        self.pushButton_isqrt = QtWidgets.QPushButton(self.LayoutWidget)
        self.pushButton_isqrt.setObjectName("pushButton_isqrt")

        self.GroupButtons.addWidget(self.pushButton_isqrt, 7, 3, 1, 1)

        # Кнопка тангенса.

        self.pushButton_tan = QtWidgets.QPushButton(self.LayoutWidget)
        self.pushButton_tan.setObjectName("pushButton_tan")

        self.GroupButtons.addWidget(self.pushButton_tan, 7, 2, 1, 1)

        # Кнопка решения.

        self.pushButton_Cal = QtWidgets.QPushButton(self.LayoutWidget)
        self.pushButton_Cal.setStyleSheet("")
        self.pushButton_Cal.setObjectName("pushButton_Cal")

        self.GroupButtons.addWidget(self.pushButton_Cal, 6, 3, 1, 1)

        self.TabsMain.addTab(self.TabsCalc, "")

        # Создание вкладки настроек.

        self.TabSettings = QtWidgets.QWidget()
        self.TabSettings.setObjectName("TabSettings")

        # Варианты тем.

        self.theme = QtWidgets.QComboBox(self.TabSettings)
        self.theme.setGeometry(QtCore.QRect(120, 190, 181, 31))
        self.theme.setObjectName("theme")
        self.theme.addItem("")
        self.theme.addItem("")
        self.theme.addItem("")
        self.theme.addItem("")
        self.theme.addItem("")
        self.theme.addItem("")
        self.theme.addItem("")
        self.theme.addItem("")
        self.theme.addItem("")
        self.theme.addItem("")
        self.theme.addItem("")
        self.theme.addItem("")
        self.theme.addItem("")
        self.theme.addItem("")
        self.theme.addItem("")
        self.theme.addItem("")
        self.theme.addItem("")
        self.theme.addItem("")
        self.theme.addItem("")

        self.label = QtWidgets.QLabel(self.TabSettings)
        self.label.setGeometry(QtCore.QRect(0, 10, 421, 81))
        self.label.setObjectName("label")

        # Кнопка переключения темы.

        self.ChangeTheme = QtWidgets.QPushButton(self.TabSettings)
        self.ChangeTheme.setGeometry(QtCore.QRect(130, 230, 161, 41))
        self.ChangeTheme.setObjectName("ChangeTheme")

        self.TabsMain.addTab(self.TabSettings, "")

        # Привязка кнопок к функциям.

        self.retranslateUi(CaculatorWin)
        self.TabsMain.setCurrentIndex(0)
        self.TabsCo.setCurrentIndex(2)
        self.pushButton_Add.clicked.connect(CaculatorWin.CalObjPressed) # type: ignore
        self.pushButton_Minus.clicked.connect(CaculatorWin.CalObjPressed) # type: ignore
        self.pushButton_Multiply.clicked.connect(CaculatorWin.CalObjPressed) # type: ignore
        self.pushButton_div.clicked.connect(CaculatorWin.CalObjPressed) # type: ignore
        self.pushButton1.clicked.connect(CaculatorWin.CalObjPressed) # type: ignore
        self.pushButton2.clicked.connect(CaculatorWin.CalObjPressed) # type: ignore
        self.pushButton3.clicked.connect(CaculatorWin.CalObjPressed) # type: ignore
        self.pushButton_dot.clicked.connect(CaculatorWin.CalObjPressed) # type: ignore
        self.pushButton4.clicked.connect(CaculatorWin.CalObjPressed) # type: ignore
        self.pushButton5.clicked.connect(CaculatorWin.CalObjPressed) # type: ignore
        self.pushButton6.clicked.connect(CaculatorWin.CalObjPressed) # type: ignore
        self.pushButton_mod.clicked.connect(CaculatorWin.CalObjPressed) # type: ignore
        self.pushButton7.clicked.connect(CaculatorWin.CalObjPressed) # type: ignore
        self.pushButton8.clicked.connect(CaculatorWin.CalObjPressed) # type: ignore
        self.pushButton9.clicked.connect(CaculatorWin.CalObjPressed) # type: ignore
        self.pushButton0.clicked.connect(CaculatorWin.CalObjPressed) # type: ignore
        self.pushButton_leftbrackets.clicked.connect(CaculatorWin.CalObjPressed) # type: ignore
        self.pushButton_rightbrackets.clicked.connect(CaculatorWin.CalObjPressed) # type: ignore
        self.pushButton_Cal.clicked.connect(CaculatorWin.ExecuteCalculate) # type: ignore
        self.pushButton_Clear.clicked.connect(CaculatorWin.ClearInput) # type: ignore
        self.ButtonUpdate.clicked.connect(CaculatorWin.Update_Result)
        self.ButtonCopy.clicked.connect(CaculatorWin.copy_elem)
        self.pushButton_sin.clicked.connect(CaculatorWin.CalObjPressed)
        self.pushButton_cos.clicked.connect(CaculatorWin.CalObjPressed)
        self.pushButton_tan.clicked.connect(CaculatorWin.CalObjPressed)
        self.pushButton_isqrt.clicked.connect(CaculatorWin.CalObjPressed)
        self.ChangeTheme.clicked.connect(CaculatorWin.change_theme)
        QtCore.QMetaObject.connectSlotsByName(CaculatorWin)

    def retranslateUi(self, CaculatorWin):
        # Перевод текста программы.

        _translate = QtCore.QCoreApplication.translate
        CaculatorWin.setWindowTitle(_translate("CaculatorWin", "Calc+"))
        self.ButtonUpdate.setText(_translate("CaculatorWin", "Обновить результаты"))
        self.ButtonCopy.setText(_translate("CaculatorWin", "Копировать"))
        self.TabsMain.setTabText(self.TabsMain.indexOf(self.TabHistory), _translate("CaculatorWin", "История"))
        self.TextMulti.setHtml(_translate("CaculatorWin", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; font-weight:600;\">Формулы сокращенного умножения:</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; text-decoration: underline;\">Квадрата суммы</span><span style=\" font-size:10pt;\">: (a + b)</span><span style=\" font-size:10pt; vertical-align:super;\">2 </span><span style=\" font-size:10pt;\">= a</span><span style=\" font-size:10pt; vertical-align:super;\">2 </span><span style=\" font-size:10pt;\">+ 2ab + b</span><span style=\" font-size:10pt; vertical-align:super;\">2</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; text-decoration: underline;\">Квадрата разности</span><span style=\" font-size:10pt;\">: (a − b)</span><span style=\" font-size:10pt; vertical-align:super;\">2 </span><span style=\" font-size:10pt;\">= a</span><span style=\" font-size:10pt; vertical-align:super;\">2 </span><span style=\" font-size:10pt;\">− 2ab + b</span><span style=\" font-size:10pt; vertical-align:super;\">2</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; text-decoration: underline;\">Куба суммы</span><span style=\" font-size:10pt;\">: (a + b)</span><span style=\" font-size:10pt; vertical-align:super;\">3 </span><span style=\" font-size:10pt;\">= a</span><span style=\" font-size:10pt; vertical-align:super;\">3 </span><span style=\" font-size:10pt;\">+ 3a2b + 3ab</span><span style=\" font-size:10pt; vertical-align:super;\">2 </span><span style=\" font-size:10pt;\">+ b</span><span style=\" font-size:10pt; vertical-align:super;\">3</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; text-decoration: underline;\">Куба разности</span><span style=\" font-size:10pt;\">: (a − b)</span><span style=\" font-size:10pt; vertical-align:super;\">3 </span><span style=\" font-size:10pt;\">= a</span><span style=\" font-size:10pt; vertical-align:super;\">3 </span><span style=\" font-size:10pt;\">− 3a2b + 3ab</span><span style=\" font-size:10pt; vertical-align:super;\">2 </span><span style=\" font-size:10pt;\">− b</span><span style=\" font-size:10pt; vertical-align:super;\">3</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; text-decoration: underline;\">Разности квадратов</span><span style=\" font-size:10pt;\">: a</span><span style=\" font-size:10pt; vertical-align:super;\">2</span><span style=\" font-size:10pt;\"> − b</span><span style=\" font-size:10pt; vertical-align:super;\">2</span><span style=\" font-size:10pt;\"> = (a − b)(a + b)</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; text-decoration: underline;\">Суммы кубов</span><span style=\" font-size:10pt;\">: a</span><span style=\" font-size:10pt; vertical-align:super;\">3 </span><span style=\" font-size:10pt;\">+ b</span><span style=\" font-size:10pt; vertical-align:super;\">3 </span><span style=\" font-size:10pt;\">= (a + b)(a</span><span style=\" font-size:10pt; vertical-align:super;\">2 </span><span style=\" font-size:10pt;\">− ab + b</span><span style=\" font-size:10pt; vertical-align:super;\">2</span><span style=\" font-size:10pt;\">)</span></p></body></html>"))
        self.TabsCo.setTabText(self.TabsCo.indexOf(self.TabMulti), _translate("CaculatorWin", "Ф. сокращенного умножения"))
        self.TextS.setHtml(_translate("CaculatorWin", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; font-weight:600;\">Формулы площадей фигур:</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; text-decoration: underline;\">Квадрат</span><span style=\" font-size:10pt;\">:</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">S = a</span><span style=\" font-size:10pt; vertical-align:super;\">2</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">S = 1/2 * d</span><span style=\" font-size:10pt; vertical-align:super;\">2</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; text-decoration: underline;\">Прямоугольник</span><span style=\" font-size:10pt;\">:</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">S = ab</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; text-decoration: underline;\">Треугольник</span><span style=\" font-size:10pt;\">:</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">S = 1/2 * ah</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">S = 1/2 * ab * sin Y</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">S = 1/2 * ac * sin B</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">S = 1/2 * bc * sin A</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; text-decoration: underline;\">Параллелограмм</span><span style=\" font-size:10pt;\">:</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">S = ah</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">S = ab * sin A</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">S = 1/2 * d</span><span style=\" font-size:10pt; vertical-align:sub;\">1</span><span style=\" font-size:10pt;\">d</span><span style=\" font-size:10pt; vertical-align:sub;\">2</span><span style=\" font-size:10pt;\"> * sin Y</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; text-decoration: underline;\">Ромб:</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">S = ah</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">S = a</span><span style=\" font-size:10pt; vertical-align:super;\">2</span><span style=\" font-size:10pt;\"> * sin A</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">S = 1/2 * d</span><span style=\" font-size:10pt; vertical-align:sub;\">1</span><span style=\" font-size:10pt;\">d</span><span style=\" font-size:10pt; vertical-align:sub;\">2</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; text-decoration: underline;\">Трапеция</span><span style=\" font-size:10pt;\">:</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">S = 1/2 * (a + b) * h</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; text-decoration: underline;\">Круг</span><span style=\" font-size:10pt;\">:</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">S = п * r</span><span style=\" font-size:10pt; vertical-align:super;\">2</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">S = 1/3 * п * d</span><span style=\" font-size:10pt; vertical-align:super;\">2</span></p></body></html>"))
        self.TabsCo.setTabText(self.TabsCo.indexOf(self.TabS), _translate("CaculatorWin", "Площади фигур"))
        self.TabsMain.setTabText(self.TabsMain.indexOf(self.TabGuide), _translate("CaculatorWin", "Справочник"))
        self.pushButton2.setText(_translate("CaculatorWin", "2"))
        self.pushButton0.setText(_translate("CaculatorWin", "0"))
        self.pushButton_leftbrackets.setText(_translate("CaculatorWin", "("))
        self.pushButton8.setText(_translate("CaculatorWin", "8"))
        self.pushButton_Clear.setText(_translate("CaculatorWin", "Clear"))
        self.pushButton4.setText(_translate("CaculatorWin", "4"))
        self.pushButton9.setText(_translate("CaculatorWin", "9"))
        self.pushButton5.setText(_translate("CaculatorWin", "5"))
        self.pushButton_cos.setText(_translate("CaculatorWin", "cos("))
        self.pushButton_dot.setText(_translate("CaculatorWin", "."))
        self.pushButton1.setText(_translate("CaculatorWin", "1"))
        self.pushButton_Add.setText(_translate("CaculatorWin", " + "))
        self.pushButton_Multiply.setText(_translate("CaculatorWin", " * "))
        self.pushButton_div.setText(_translate("CaculatorWin", " / "))
        self.pushButton_rightbrackets.setText(_translate("CaculatorWin", ")"))
        self.pushButton_mod.setText(_translate("CaculatorWin", " % "))
        self.pushButton_sin.setText(_translate("CaculatorWin", "sin("))
        self.pushButton3.setText(_translate("CaculatorWin", "3"))
        self.pushButton6.setText(_translate("CaculatorWin", "6"))
        self.pushButton7.setText(_translate("CaculatorWin", "7"))
        self.pushButton_Minus.setText(_translate("CaculatorWin", " - "))
        self.pushButton_isqrt.setText(_translate("CaculatorWin", "isqrt("))
        self.pushButton_tan.setText(_translate("CaculatorWin", "tan("))
        self.pushButton_Cal.setText(_translate("CaculatorWin", "="))
        self.TabsMain.setTabText(self.TabsMain.indexOf(self.TabsCalc), _translate("CaculatorWin", "Калькулятор"))
        self.theme.setItemText(0, _translate("CaculatorWin", "dark_amber"))
        self.theme.setItemText(1, _translate("CaculatorWin", "dark_blue"))
        self.theme.setItemText(2, _translate("CaculatorWin", "dark_cyan"))
        self.theme.setItemText(3, _translate("CaculatorWin", "dark_lightgreen"))
        self.theme.setItemText(4, _translate("CaculatorWin", "dark_pink"))
        self.theme.setItemText(5, _translate("CaculatorWin", "dark_purple"))
        self.theme.setItemText(6, _translate("CaculatorWin", "dark_red"))
        self.theme.setItemText(7, _translate("CaculatorWin", "dark_teal"))
        self.theme.setItemText(8, _translate("CaculatorWin", "dark_yellow"))
        self.theme.setItemText(9, _translate("CaculatorWin", "light_amber"))
        self.theme.setItemText(10, _translate("CaculatorWin", "light_blue"))
        self.theme.setItemText(11, _translate("CaculatorWin", "light_cyan"))
        self.theme.setItemText(12, _translate("CaculatorWin", "light_cyan_500"))
        self.theme.setItemText(13, _translate("CaculatorWin", "light_lightgreen"))
        self.theme.setItemText(14, _translate("CaculatorWin", "light_pink"))
        self.theme.setItemText(15, _translate("CaculatorWin", "light_purple"))
        self.theme.setItemText(16, _translate("CaculatorWin", "light_red"))
        self.theme.setItemText(17, _translate("CaculatorWin", "light_teal"))
        self.theme.setItemText(18, _translate("CaculatorWin", "light_yellow"))
        self.label.setText(_translate("CaculatorWin",
                                      "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600;\">Темы</span></p></body></html>"))
        self.ChangeTheme.setText(_translate("CaculatorWin", "Сменить тему"))
        self.TabsMain.setTabText(self.TabsMain.indexOf(self.TabSettings), _translate("CaculatorWin", "Настройки"))
