# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calc.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

# Класс инициализации программы.


class Ui_CaculatorWin(object):
    def setupUi(self, CaculatorWin):
        # Найстройка размера окна программы.
        weight = 440
        height = 450
        CaculatorWin.setObjectName("CaculatorWin")
        CaculatorWin.resize(weight, height)

        # Фиксирование размера окна.

        CaculatorWin.setMinimumSize(QtCore.QSize(weight, height))
        CaculatorWin.setMaximumSize(QtCore.QSize(weight, height))

        # Добавление иконки.

        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("icon.png"), QtGui.QIcon.Selected, QtGui.QIcon.On)
        CaculatorWin.setWindowIcon(icon)

        self.row_lable = ["Запрос", "Ответ"]

        # Инициализация вкладок программы.

        self.tabWidget = QtWidgets.QTabWidget(CaculatorWin)
        self.tabWidget.setGeometry(QtCore.QRect(6, -1, 431, 451))
        self.tabWidget.setObjectName("tabWidget")

        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")

        self.pushButton_update = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_update.setGeometry(QtCore.QRect(0, 375, 221, 41))
        self.pushButton_update.setObjectName("pushButton_update")

        self.tableWidget = QtWidgets.QTableWidget(self.tab_2)
        self.tableWidget.setGeometry(QtCore.QRect(5, 11, 411, 355))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(0)

        self.pushButton_copy = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_copy.setGeometry(QtCore.QRect(230, 375, 191, 41))
        self.pushButton_copy.setObjectName("pushButton_copy")

        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")

        self.tabWidget_multi = QtWidgets.QTabWidget(self.tab_3)
        self.tabWidget_multi.setGeometry(QtCore.QRect(-4, -1, 431, 431))
        self.tabWidget_multi.setObjectName("tabWidget_multi")

        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")

        self.textBrowser_2 = QtWidgets.QTextBrowser(self.tab_4)
        self.textBrowser_2.setGeometry(QtCore.QRect(10, 5, 411, 380))
        self.textBrowser_2.setObjectName("textBrowser_2")

        self.tabWidget_multi.addTab(self.tab_4, "")

        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")

        self.textBrowser = QtWidgets.QTextBrowser(self.tab_5)
        self.textBrowser.setGeometry(QtCore.QRect(10, 5, 411, 380))
        self.textBrowser.setObjectName("textBrowser")

        self.tabWidget_multi.addTab(self.tab_5, "")

        self.tabWidget.addTab(self.tab_3, "")

        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")

        self.CalculatorDisplay = QtWidgets.QTextBrowser(self.tab)
        self.CalculatorDisplay.setGeometry(QtCore.QRect(4, 10, 421, 131))
        self.CalculatorDisplay.setObjectName("CalculatorDisplay")

        self.gridLayoutWidget = QtWidgets.QWidget(self.tab)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(4, 149, 421, 261))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")

        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")

        self.pushButton2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton2.setObjectName("pushButton2")

        self.gridLayout_2.addWidget(self.pushButton2, 2, 1, 1, 1)

        self.pushButton0 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton0.setObjectName("pushButton0")

        self.gridLayout_2.addWidget(self.pushButton0, 6, 0, 1, 1)

        self.pushButton_leftbrackets = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_leftbrackets.setObjectName("pushButton_leftbrackets")

        self.gridLayout_2.addWidget(self.pushButton_leftbrackets, 6, 1, 1, 1)

        self.pushButton8 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton8.setObjectName("pushButton8")

        self.gridLayout_2.addWidget(self.pushButton8, 4, 1, 1, 1)

        self.pushButton_Clear = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_Clear.setObjectName("pushButton_Clear")

        self.gridLayout_2.addWidget(self.pushButton_Clear, 4, 3, 1, 1)

        self.pushButton4 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton4.setObjectName("pushButton4")

        self.gridLayout_2.addWidget(self.pushButton4, 3, 0, 1, 1)

        self.pushButton9 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton9.setObjectName("pushButton9")

        self.gridLayout_2.addWidget(self.pushButton9, 4, 2, 1, 1)

        self.pushButton5 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton5.setObjectName("pushButton5")

        self.gridLayout_2.addWidget(self.pushButton5, 3, 1, 1, 1)

        self.pushButton_cos = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_cos.setObjectName("pushButton_cos")

        self.gridLayout_2.addWidget(self.pushButton_cos, 7, 1, 1, 1)

        self.pushButton_dot = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_dot.setObjectName("pushButton_dot")

        self.gridLayout_2.addWidget(self.pushButton_dot, 2, 3, 1, 1)

        self.pushButton1 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton1.setObjectName("pushButton1")

        self.gridLayout_2.addWidget(self.pushButton1, 2, 0, 1, 1)

        self.pushButton_Add = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_Add.setObjectName("pushButton_Add")

        self.gridLayout_2.addWidget(self.pushButton_Add, 0, 0, 1, 1)

        self.pushButton_Multiply = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_Multiply.setObjectName("pushButton_Multiply")

        self.gridLayout_2.addWidget(self.pushButton_Multiply, 0, 2, 1, 1)

        self.pushButton_div = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_div.setObjectName("pushButton_div")

        self.gridLayout_2.addWidget(self.pushButton_div, 0, 3, 1, 1)

        self.pushButton_rightbrackets = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_rightbrackets.setObjectName("pushButton_rightbrackets")

        self.gridLayout_2.addWidget(self.pushButton_rightbrackets, 6, 2, 1, 1)

        self.pushButton_mod = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_mod.setObjectName("pushButton_mod")

        self.gridLayout_2.addWidget(self.pushButton_mod, 3, 3, 1, 1)

        self.pushButton_sin = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_sin.setObjectName("pushButton_sin")

        self.gridLayout_2.addWidget(self.pushButton_sin, 7, 0, 1, 1)

        self.pushButton3 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton3.setObjectName("pushButton3")

        self.gridLayout_2.addWidget(self.pushButton3, 2, 2, 1, 1)

        self.pushButton6 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton6.setObjectName("pushButton6")

        self.gridLayout_2.addWidget(self.pushButton6, 3, 2, 1, 1)

        self.pushButton7 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton7.setObjectName("pushButton7")

        self.gridLayout_2.addWidget(self.pushButton7, 4, 0, 1, 1)

        self.pushButton_Minus = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_Minus.setObjectName("pushButton_Minus")

        self.gridLayout_2.addWidget(self.pushButton_Minus, 0, 1, 1, 1)

        self.pushButton_ctg = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_ctg.setObjectName("pushButton_ctg")

        self.gridLayout_2.addWidget(self.pushButton_ctg, 7, 3, 1, 1)

        self.pushButton_tan = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_tan.setObjectName("pushButton_tan")

        self.gridLayout_2.addWidget(self.pushButton_tan, 7, 2, 1, 1)

        self.pushButton_Cal = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_Cal.setStyleSheet("")
        self.pushButton_Cal.setObjectName("pushButton_Cal")

        self.gridLayout_2.addWidget(self.pushButton_Cal, 6, 3, 1, 1)

        self.tabWidget.addTab(self.tab, "")

        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")

        self.theme = QtWidgets.QComboBox(self.tab_7)
        self.theme.setGeometry(QtCore.QRect(120, 190, 181, 31))
        self.theme.setObjectName("theme")
        self.theme.addItem("")
        self.theme.addItem("")
        self.theme.addItem("")
        self.theme.addItem("")
        self.theme.addItem("")
        self.theme.addItem("")
        self.theme.addItem("")
        self.theme.addItem("")
        self.theme.addItem("")
        self.theme.addItem("")
        self.theme.addItem("")
        self.theme.addItem("")
        self.theme.addItem("")
        self.theme.addItem("")
        self.theme.addItem("")
        self.theme.addItem("")
        self.theme.addItem("")
        self.theme.addItem("")
        self.theme.addItem("")

        self.label = QtWidgets.QLabel(self.tab_7)
        self.label.setGeometry(QtCore.QRect(0, 10, 421, 81))
        self.label.setObjectName("label")

        self.pushButton = QtWidgets.QPushButton(self.tab_7)
        self.pushButton.setGeometry(QtCore.QRect(130, 230, 161, 41))
        self.pushButton.setObjectName("pushButton")

        self.tabWidget.addTab(self.tab_7, "")

        self.retranslateUi(CaculatorWin)
        self.tabWidget.setCurrentIndex(0)
        self.tabWidget_multi.setCurrentIndex(2)
        self.pushButton_Add.clicked.connect(CaculatorWin.CalObjPressed) # type: ignore
        self.pushButton_Minus.clicked.connect(CaculatorWin.CalObjPressed) # type: ignore
        self.pushButton_Multiply.clicked.connect(CaculatorWin.CalObjPressed) # type: ignore
        self.pushButton_div.clicked.connect(CaculatorWin.CalObjPressed) # type: ignore
        self.pushButton1.clicked.connect(CaculatorWin.CalObjPressed) # type: ignore
        self.pushButton2.clicked.connect(CaculatorWin.CalObjPressed) # type: ignore
        self.pushButton3.clicked.connect(CaculatorWin.CalObjPressed) # type: ignore
        self.pushButton_dot.clicked.connect(CaculatorWin.CalObjPressed) # type: ignore
        self.pushButton4.clicked.connect(CaculatorWin.CalObjPressed) # type: ignore
        self.pushButton5.clicked.connect(CaculatorWin.CalObjPressed) # type: ignore
        self.pushButton6.clicked.connect(CaculatorWin.CalObjPressed) # type: ignore
        self.pushButton_mod.clicked.connect(CaculatorWin.CalObjPressed) # type: ignore
        self.pushButton7.clicked.connect(CaculatorWin.CalObjPressed) # type: ignore
        self.pushButton8.clicked.connect(CaculatorWin.CalObjPressed) # type: ignore
        self.pushButton9.clicked.connect(CaculatorWin.CalObjPressed) # type: ignore
        self.pushButton0.clicked.connect(CaculatorWin.CalObjPressed) # type: ignore
        self.pushButton_leftbrackets.clicked.connect(CaculatorWin.CalObjPressed) # type: ignore
        self.pushButton_rightbrackets.clicked.connect(CaculatorWin.CalObjPressed) # type: ignore
        self.pushButton_Cal.clicked.connect(CaculatorWin.ExecuteCalculate) # type: ignore
        self.pushButton_Clear.clicked.connect(CaculatorWin.ClearInput) # type: ignore
        self.pushButton_update.clicked.connect(CaculatorWin.Update_Result)
        self.pushButton_copy.clicked.connect(CaculatorWin.copy_elem)
        self.pushButton_sin.clicked.connect(CaculatorWin.CalObjPressed)
        self.pushButton_cos.clicked.connect(CaculatorWin.CalObjPressed)
        self.pushButton_tan.clicked.connect(CaculatorWin.CalObjPressed)
        self.pushButton.clicked.connect(CaculatorWin.change_theme)
        QtCore.QMetaObject.connectSlotsByName(CaculatorWin)

    def retranslateUi(self, CaculatorWin):
        _translate = QtCore.QCoreApplication.translate
        CaculatorWin.setWindowTitle(_translate("CaculatorWin", "Calc+"))
        self.pushButton_update.setText(_translate("CaculatorWin", "Обновить результаты"))
        self.pushButton_copy.setText(_translate("CaculatorWin", "Копировать"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("CaculatorWin", "История"))
        self.textBrowser_2.setHtml(_translate("CaculatorWin", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; font-weight:600;\">Формулы сокращенного умножения:</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; text-decoration: underline;\">Квадрата суммы</span><span style=\" font-size:10pt;\">: (a + b)</span><span style=\" font-size:10pt; vertical-align:super;\">2 </span><span style=\" font-size:10pt;\">= a</span><span style=\" font-size:10pt; vertical-align:super;\">2 </span><span style=\" font-size:10pt;\">+ 2ab + b</span><span style=\" font-size:10pt; vertical-align:super;\">2</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; text-decoration: underline;\">Квадрата разности</span><span style=\" font-size:10pt;\">: (a − b)</span><span style=\" font-size:10pt; vertical-align:super;\">2 </span><span style=\" font-size:10pt;\">= a</span><span style=\" font-size:10pt; vertical-align:super;\">2 </span><span style=\" font-size:10pt;\">− 2ab + b</span><span style=\" font-size:10pt; vertical-align:super;\">2</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; text-decoration: underline;\">Куба суммы</span><span style=\" font-size:10pt;\">: (a + b)</span><span style=\" font-size:10pt; vertical-align:super;\">3 </span><span style=\" font-size:10pt;\">= a</span><span style=\" font-size:10pt; vertical-align:super;\">3 </span><span style=\" font-size:10pt;\">+ 3a2b + 3ab</span><span style=\" font-size:10pt; vertical-align:super;\">2 </span><span style=\" font-size:10pt;\">+ b</span><span style=\" font-size:10pt; vertical-align:super;\">3</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; text-decoration: underline;\">Куба разности</span><span style=\" font-size:10pt;\">: (a − b)</span><span style=\" font-size:10pt; vertical-align:super;\">3 </span><span style=\" font-size:10pt;\">= a</span><span style=\" font-size:10pt; vertical-align:super;\">3 </span><span style=\" font-size:10pt;\">− 3a2b + 3ab</span><span style=\" font-size:10pt; vertical-align:super;\">2 </span><span style=\" font-size:10pt;\">− b</span><span style=\" font-size:10pt; vertical-align:super;\">3</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; text-decoration: underline;\">Разности квадратов</span><span style=\" font-size:10pt;\">: a</span><span style=\" font-size:10pt; vertical-align:super;\">2</span><span style=\" font-size:10pt;\"> − b</span><span style=\" font-size:10pt; vertical-align:super;\">2</span><span style=\" font-size:10pt;\"> = (a − b)(a + b)</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; text-decoration: underline;\">Суммы кубов</span><span style=\" font-size:10pt;\">: a</span><span style=\" font-size:10pt; vertical-align:super;\">3 </span><span style=\" font-size:10pt;\">+ b</span><span style=\" font-size:10pt; vertical-align:super;\">3 </span><span style=\" font-size:10pt;\">= (a + b)(a</span><span style=\" font-size:10pt; vertical-align:super;\">2 </span><span style=\" font-size:10pt;\">− ab + b</span><span style=\" font-size:10pt; vertical-align:super;\">2</span><span style=\" font-size:10pt;\">)</span></p></body></html>"))
        self.tabWidget_multi.setTabText(self.tabWidget_multi.indexOf(self.tab_4), _translate("CaculatorWin", "Ф. сокращенного умножения"))
        self.textBrowser.setHtml(_translate("CaculatorWin", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; font-weight:600;\">Формулы площадей фигур:</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; text-decoration: underline;\">Квадрат</span><span style=\" font-size:10pt;\">:</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">S = a</span><span style=\" font-size:10pt; vertical-align:super;\">2</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">S = 1/2 * d</span><span style=\" font-size:10pt; vertical-align:super;\">2</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; text-decoration: underline;\">Прямоугольник</span><span style=\" font-size:10pt;\">:</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">S = ab</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; text-decoration: underline;\">Треугольник</span><span style=\" font-size:10pt;\">:</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">S = 1/2 * ah</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">S = 1/2 * ab * sin Y</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">S = 1/2 * ac * sin B</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">S = 1/2 * bc * sin A</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; text-decoration: underline;\">Параллелограмм</span><span style=\" font-size:10pt;\">:</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">S = ah</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">S = ab * sin A</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">S = 1/2 * d</span><span style=\" font-size:10pt; vertical-align:sub;\">1</span><span style=\" font-size:10pt;\">d</span><span style=\" font-size:10pt; vertical-align:sub;\">2</span><span style=\" font-size:10pt;\"> * sin Y</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; text-decoration: underline;\">Ромб:</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">S = ah</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">S = a</span><span style=\" font-size:10pt; vertical-align:super;\">2</span><span style=\" font-size:10pt;\"> * sin A</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">S = 1/2 * d</span><span style=\" font-size:10pt; vertical-align:sub;\">1</span><span style=\" font-size:10pt;\">d</span><span style=\" font-size:10pt; vertical-align:sub;\">2</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; text-decoration: underline;\">Трапеция</span><span style=\" font-size:10pt;\">:</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">S = 1/2 * (a + b) * h</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt; text-decoration: underline;\">Круг</span><span style=\" font-size:10pt;\">:</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">S = п * r</span><span style=\" font-size:10pt; vertical-align:super;\">2</span></p>\n"
"<p style=\" margin-top:12px; margin-bottom:12px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">S = 1/3 * п * d</span><span style=\" font-size:10pt; vertical-align:super;\">2</span></p></body></html>"))
        self.tabWidget_multi.setTabText(self.tabWidget_multi.indexOf(self.tab_5), _translate("CaculatorWin", "Площади фигур"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("CaculatorWin", "Справочник"))
        self.pushButton2.setText(_translate("CaculatorWin", "2"))
        self.pushButton0.setText(_translate("CaculatorWin", "0"))
        self.pushButton_leftbrackets.setText(_translate("CaculatorWin", "("))
        self.pushButton8.setText(_translate("CaculatorWin", "8"))
        self.pushButton_Clear.setText(_translate("CaculatorWin", "Clear"))
        self.pushButton4.setText(_translate("CaculatorWin", "4"))
        self.pushButton9.setText(_translate("CaculatorWin", "9"))
        self.pushButton5.setText(_translate("CaculatorWin", "5"))
        self.pushButton_cos.setText(_translate("CaculatorWin", "cos("))
        self.pushButton_dot.setText(_translate("CaculatorWin", "."))
        self.pushButton1.setText(_translate("CaculatorWin", "1"))
        self.pushButton_Add.setText(_translate("CaculatorWin", " + "))
        self.pushButton_Multiply.setText(_translate("CaculatorWin", " * "))
        self.pushButton_div.setText(_translate("CaculatorWin", " / "))
        self.pushButton_rightbrackets.setText(_translate("CaculatorWin", ")"))
        self.pushButton_mod.setText(_translate("CaculatorWin", " % "))
        self.pushButton_sin.setText(_translate("CaculatorWin", "sin("))
        self.pushButton3.setText(_translate("CaculatorWin", "3"))
        self.pushButton6.setText(_translate("CaculatorWin", "6"))
        self.pushButton7.setText(_translate("CaculatorWin", "7"))
        self.pushButton_Minus.setText(_translate("CaculatorWin", " - "))
        self.pushButton_ctg.setText(_translate("CaculatorWin", "--------"))
        self.pushButton_tan.setText(_translate("CaculatorWin", "tan("))
        self.pushButton_Cal.setText(_translate("CaculatorWin", "="))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("CaculatorWin", "Калькулятор"))
        self.theme.setItemText(0, _translate("CaculatorWin", "dark_amber"))
        self.theme.setItemText(1, _translate("CaculatorWin", "dark_blue"))
        self.theme.setItemText(2, _translate("CaculatorWin", "dark_cyan"))
        self.theme.setItemText(3, _translate("CaculatorWin", "dark_lightgreen"))
        self.theme.setItemText(4, _translate("CaculatorWin", "dark_pink"))
        self.theme.setItemText(5, _translate("CaculatorWin", "dark_purple"))
        self.theme.setItemText(6, _translate("CaculatorWin", "dark_red"))
        self.theme.setItemText(7, _translate("CaculatorWin", "dark_teal"))
        self.theme.setItemText(8, _translate("CaculatorWin", "dark_yellow"))
        self.theme.setItemText(9, _translate("CaculatorWin", "light_amber"))
        self.theme.setItemText(10, _translate("CaculatorWin", "light_blue"))
        self.theme.setItemText(11, _translate("CaculatorWin", "light_cyan"))
        self.theme.setItemText(12, _translate("CaculatorWin", "light_cyan_500"))
        self.theme.setItemText(13, _translate("CaculatorWin", "light_lightgreen"))
        self.theme.setItemText(14, _translate("CaculatorWin", "light_pink"))
        self.theme.setItemText(15, _translate("CaculatorWin", "light_purple"))
        self.theme.setItemText(16, _translate("CaculatorWin", "light_red"))
        self.theme.setItemText(17, _translate("CaculatorWin", "light_teal"))
        self.theme.setItemText(18, _translate("CaculatorWin", "light_yellow"))
        self.label.setText(_translate("CaculatorWin",
                                      "<html><head/><body><p align=\"center\"><span style=\" font-size:14pt; font-weight:600;\">Темы</span></p></body></html>"))
        self.pushButton.setText(_translate("CaculatorWin", "Сменить тему"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_7), _translate("CaculatorWin", "Настройки"))
